# Generated by Django 4.0.4 on 2023-11-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_experience_semester_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='active_session',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
