# Generated by Django 4.0.4 on 2023-11-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_session_active_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='year',
            field=models.PositiveIntegerField(default=2023, help_text='e.g. 2023'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2023, help_text='e.g. 2023'),
            preserve_default=False,
        ),
    ]
