# Generated by Django 4.0.4 on 2023-11-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_session_year_student_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 2023'),
        ),
    ]
