# Generated by Django 4.0.4 on 2023-11-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_graduation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='end_date',
        ),
    ]
