# Generated by Django 4.0.4 on 2023-11-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_semester_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(default='2023-09-11'),
            preserve_default=False,
        ),
    ]
