# Generated by Django 3.2.12 on 2024-02-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_semester_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.semester'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
